### ISSUE TITLE
Problem install on linux - cannot compile crypto

### ISSUE THREAD

**Issue by kamiljaszczynski** [assembl/assembl#140]
Hello,
Wt try to install it on debian. 
We have some problem with crypto modules:

[localhost] out:     generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
[localhost] out:     building '_openssl' extension
 x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
[localhost] out:     build/temp.linux-x86_64-2.7/_openssl.c:606:5: error: conflicting types for ‘i2d_ASN1_OBJECT’
[localhost] out:      int i2d_ASN1_OBJECT(ASN1_OBJECT *, unsigned char **);

[localhost] out:     build/temp.linux-x86_64-2.7/_openssl.c:74705:5: note: (near initialization for ‘_cffi_struct_unions[133].size’)
[localhost] out:     In file included from /usr/include/sched.h:28:0,
[localhost] out:                      from /usr/include/pthread.h:23,
[localhost] out:                      from /usr/include/openssl/crypto.h:406,
[localhost] out:                      from /usr/include/openssl/bio.h:20,
[localhost] out:                      from /usr/include/openssl/asn1.h:16,
[localhost] out:                      from build/temp.linux-x86_64-2.7/_openssl.c:445:
[localhost] out:     build/temp.linux-x86_64-2.7/_openssl.c:74705:29: error: initializer element is not constant
[localhost] out:          sizeof(X509_STORE_CTX), offsetof(struct _cffi_align__X509_STORE_CTX, y), 96, 10 },
[localhost] out:                                  ^
[localhost] out:     build/temp.linux-x86_64-2.7/_openssl.c:74705:29: note: (near initialization for ‘_cffi_struct_unions[133].alignment’)
[localhost] out:     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
[localhost] out: Command "/root/assembl/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-otFlGK/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-exDY2T-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/assembl/venv/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-otFlGK/cryptography/
[localhost] out: 

Maybe we use wrong gcc version or something?

Somebody have the same problem ?

**Comment by kamiljaszczynski** [comment]
Change cryptography version to higher helps.

**Comment by vincentfretin** [comment]
Which version of debian? stretch? We didn't test it with stretch yet.
I'm the only one using debian on desktop apparently, the jessie version. All the servers are on Ubuntu 16.04 and the other developers are using Ubuntu or macOS.

Which version of crypto works for you?

**Comment by kamiljaszczynski** [comment]
Debian 9 (Stretch) 
We change cryptography to cryptography==2.0.3
And now is another problem:

[localhost] out: mesg: ttyname failed: Inappropriate ioctl for device
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/root/assembl/venv/bin/pip", line 7, in <module>
[localhost] out:     from pip import main
[localhost] out:   File "/root/assembl/venv/local/lib/python2.7/site-packages/pip/__init__.py", line 21, in <module>
[localhost] out:     from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
[localhost] out:   File "/root/assembl/venv/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 64, in <module>
[localhost] out:     vendored("cachecontrol")
[localhost] out:   File "/root/assembl/venv/local/lib/python2.7/site-packages/pip/_vendor/__init__.py", line 36, in vendored
[localhost] out:     __import__(modulename, globals(), locals(), level=0)
[localhost] out:   File "/root/assembl/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
[localhost] out:   File "/root/assembl/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
[localhost] out:   File "/root/assembl/venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 4, in <module>
[localhost] out:   File "/root/assembl/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/__init__.py", line 52, in <module>
[localhost] out:   File "/root/assembl/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 59, in <module>
[localhost] out:   File "/root/assembl/venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/packages/__init__.py", line 32, in vendored
[localhost] out:   File "/root/assembl/venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 47, in <module>
[localhost] out:   File "/root/assembl/venv/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
[localhost] out:     from OpenSSL import rand, crypto, SSL
[localhost] out:   File "/root/assembl/venv/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 124, in <module>
[localhost] out:     SSL_ST_INIT = _lib.SSL_ST_INIT
[localhost] out: AttributeError: 'module' object has no attribute 'SSL_ST_INIT'


I found that pyOpenSSL==16.2.0
should help but not.

**Comment by vincentfretin** [comment]
It should work with pyOpenSSL 16.2.0 or 17.2.0. I tested it on one of my stretch server in a new virtualenv.
```
vincentfretin@staging:~$ mkvirtualenv test
New python executable in /home/vincentfretin/.virtualenvs/test/bin/python2.7
Also creating executable in /home/vincentfretin/.virtualenvs/test/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/vincentfretin/.virtualenvs/test/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/vincentfretin/.virtualenvs/test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/vincentfretin/.virtualenvs/test/bin/preactivate
virtualenvwrapper.user_scripts creating /home/vincentfretin/.virtualenvs/test/bin/postactivate
virtualenvwrapper.user_scripts creating /home/vincentfretin/.virtualenvs/test/bin/get_env_details
(test) vincentfretin@staging:~$ mkvirtualenv test
New python executable in /home/vincentfretin/.virtualenvs/test/bin/python2.7
Not overwriting existing python script /home/vincentfretin/.virtualenvs/test/bin/python (you must use /home/vincentfretin/.virtualenvs/test/bin/python2.7)
Installing setuptools, pip, wheel...done.
(test) vincentfretin@staging:~$ pip install cryptography
Collecting cryptography
  Using cached cryptography-2.0.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting ipaddress (from cryptography)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting six>=1.4.1 (from cryptography)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography)
  Using cached asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting cffi>=1.7 (from cryptography)
  Using cached cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34 (from cryptography)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pycparser (from cffi>=1.7->cryptography)
Installing collected packages: ipaddress, six, idna, asn1crypto, pycparser, cffi, enum34, cryptography
Successfully installed asn1crypto-0.22.0 cffi-1.10.0 cryptography-2.0.3 enum34-1.1.6 idna-2.6 ipaddress-1.0.18 pycparser-2.18 six-1.10.0
(test) vincentfretin@staging:~$ pip install pyOpenSSL==16.0.0
Collecting pyOpenSSL==16.0.0
  Using cached pyOpenSSL-16.0.0-py2.py3-none-any.whl
Requirement already satisfied: cryptography>=1.3 in ./.virtualenvs/test/lib/python2.7/site-packages (from pyOpenSSL==16.0.0)
Requirement already satisfied: six>=1.5.2 in ./.virtualenvs/test/lib/python2.7/site-packages (from pyOpenSSL==16.0.0)
Requirement already satisfied: ipaddress in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL==16.0.0)
Requirement already satisfied: idna>=2.1 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL==16.0.0)
Requirement already satisfied: asn1crypto>=0.21.0 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL==16.0.0)
Requirement already satisfied: cffi>=1.7 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL==16.0.0)
Requirement already satisfied: enum34 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL==16.0.0)
Requirement already satisfied: pycparser in ./.virtualenvs/test/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.3->pyOpenSSL==16.0.0)
Installing collected packages: pyOpenSSL
Successfully installed pyOpenSSL-16.0.0
(test) vincentfretin@staging:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import rand, crypto, SSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vincentfretin/.virtualenvs/test/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/vincentfretin/.virtualenvs/test/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
>>> 
(test) vincentfretin@staging:~$ pip install pyOpenSSL==16.2.0
Collecting pyOpenSSL==16.2.0
  Using cached pyOpenSSL-16.2.0-py2.py3-none-any.whl
Requirement already satisfied: cryptography>=1.3.4 in ./.virtualenvs/test/lib/python2.7/site-packages (from pyOpenSSL==16.2.0)
Requirement already satisfied: six>=1.5.2 in ./.virtualenvs/test/lib/python2.7/site-packages (from pyOpenSSL==16.2.0)
Requirement already satisfied: ipaddress in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3.4->pyOpenSSL==16.2.0)
Requirement already satisfied: idna>=2.1 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3.4->pyOpenSSL==16.2.0)
Requirement already satisfied: asn1crypto>=0.21.0 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3.4->pyOpenSSL==16.2.0)
Requirement already satisfied: cffi>=1.7 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3.4->pyOpenSSL==16.2.0)
Requirement already satisfied: enum34 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.3.4->pyOpenSSL==16.2.0)
Requirement already satisfied: pycparser in ./.virtualenvs/test/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.3.4->pyOpenSSL==16.2.0)
Installing collected packages: pyOpenSSL
  Found existing installation: pyOpenSSL 16.0.0
    Uninstalling pyOpenSSL-16.0.0:
      Successfully uninstalled pyOpenSSL-16.0.0
Successfully installed pyOpenSSL-16.2.0
(test) vincentfretin@staging:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import rand, crypto, SSL
>>> 
(test) vincentfretin@staging:~$ pip install pyOpenSSL==17.2.0
Collecting pyOpenSSL==17.2.0
  Using cached pyOpenSSL-17.2.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5.2 in ./.virtualenvs/test/lib/python2.7/site-packages (from pyOpenSSL==17.2.0)
Requirement already satisfied: cryptography>=1.9 in ./.virtualenvs/test/lib/python2.7/site-packages (from pyOpenSSL==17.2.0)
Requirement already satisfied: ipaddress in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.9->pyOpenSSL==17.2.0)
Requirement already satisfied: cffi>=1.7 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.9->pyOpenSSL==17.2.0)
Requirement already satisfied: idna>=2.1 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.9->pyOpenSSL==17.2.0)
Requirement already satisfied: asn1crypto>=0.21.0 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.9->pyOpenSSL==17.2.0)
Requirement already satisfied: enum34 in ./.virtualenvs/test/lib/python2.7/site-packages (from cryptography>=1.9->pyOpenSSL==17.2.0)
Requirement already satisfied: pycparser in ./.virtualenvs/test/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.9->pyOpenSSL==17.2.0)
Installing collected packages: pyOpenSSL
  Found existing installation: pyOpenSSL 16.2.0
    Uninstalling pyOpenSSL-16.2.0:
      Successfully uninstalled pyOpenSSL-16.2.0
Successfully installed pyOpenSSL-17.2.0
(test) vincentfretin@staging:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import rand, crypto, SSL
>>>
```

**Comment by kamiljaszczynski** [comment]
I use also pyOpenSSL-17.2.0
in requirements.txt.

Maybe i need clean all project or get fresh one.
I found:
venv/lib/python2.7/site-packages/pyOpenSSL-16.0.0.dist-info/

**Comment by vincentfretin** [comment]
Yes try to clean it up, remove the venv directory I guess.

**Comment by vincentfretin** [comment]
@maparent is this safe to upgrade to cryptography==2.0.3 and pyOpenSSL==17.2.0 ?
The only code that is using cryptography is assembl/auth/make_saml.py AFAICT. I don't know how to test that it won't break something on this saml side.

**Comment by kamiljaszczynski** [comment]
Working after clean ( remove venv ). But is another problem:

Upgrading node
Asking supervisor to stop dev:gulp
Supervisord doesn't seem to be running, nothing to stop
[localhost] run: cd /root/assembl && . /root/assembl/venv/bin/activate &&
nodeenv --node=6.1.0 --npm=3.8.6 --python-virtualenv assembl/static/js
[localhost] out: mesg: ttyname failed: Inappropriate ioctl for device
[localhost] out:  * Install prebuilt node (6.1.0) ....Traceback (most
recent call last):
[localhost] out:   File "/root/assembl/venv/bin/nodeenv", line 11, in
<module>
[localhost] out:     load_entry_point('nodeenv', 'console_scripts',
'nodeenv')()
[localhost] out:   File "/root/assembl/venv/src/nodeenv/nodeenv.py", line
1060, in main
[localhost] out:     create_environment(env_dir, opt)
[localhost] out:   File "/root/assembl/venv/src/nodeenv/nodeenv.py", line
891, in create_environment
[localhost] out:     install_node(env_dir, src_dir, opt)
[localhost] out:   File "/root/assembl/venv/src/nodeenv/nodeenv.py", line
692, in install_node
[localhost] out:     copy_node_from_prebuilt(env_dir, src_dir, opt.node)
[localhost] out:   File "/root/assembl/venv/src/nodeenv/nodeenv.py", line
603, in copy_node_from_prebuilt
[localhost] out:     copytree(src_folder, env_dir, True)
[localhost] out:   File "/root/assembl/venv/src/nodeenv/nodeenv.py", line
575, in copytree
[localhost] out:     copytree(s, d, symlinks, ignore)
[localhost] out:   File "/root/assembl/venv/src/nodeenv/nodeenv.py", line
578, in copytree
[localhost] out:     os.symlink(os.readlink(s), d)
[localhost] out: OSError: [Errno 17] File exists
[localhost] out:


Fatal error: run() received nonzero return code 1 while executing!

Requested: cd /root/assembl && . /root/assembl/venv/bin/activate && nodeenv
--node=6.1.0 --npm=3.8.6 --python-virtualenv assembl/static/js
Executed: /bin/bash -l -c "cd /root/assembl && .
/root/assembl/venv/bin/activate && nodeenv --node=6.1.0 --npm=3.8.6
--python-virtualenv assembl/static/js"

Aborting.
Disconnecting from localhost... done.


And Was problem with postgress. We need configure postgress to work from
localhost?

**Comment by kamiljaszczynski** [comment]
Something like this helpd:

- open /root/.profile

- remove the offensive line

- replace it with:

tty -s && mesg n

**Comment by vincentfretin** [comment]
Hum, I'm not sure why you have this `OSError: [Errno 17] File exists` error here. you may need to debug it yourself by adding `import pdb;pdb.set_trace() in nodeenv.py
For postgres, I guess the necessary config is done in fabfile.py.

**Comment by vincentfretin** [comment]
Btw, you shouldn't execute the fab command as root but as a regular user, it will sudo some of the commands automatically if needed.

**Comment by kamiljaszczynski** [comment]
I think is work now :)

[localhost] Executing task 'app_reload'

Warning: run() received nonzero return code 2 while executing 'cd
/root/assembl && . /root/assembl/venv/bin/activate && supervisorctl avail'!

[localhost] Executing task 'webservers_reload'

Done.
Disconnecting from localhost... done.
sudo fab -c configs/develop.rc bootstrap_from_checkout  5.36s user 1.34s
system 1% cpu 6:38.80 total


Thanks for help ! :>

**Comment by kamiljaszczynski** [comment]
Where can i find logs?
When i'm login  i get:
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

I try to find last modified files in assembl folder but there are not log there ;)

**Comment by vincentfretin** [comment]
`supervisorctl tail -f dev:pserve stderr`

**Comment by kamiljaszczynski** [comment]
Thanks :>

I found reaseon:

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc3040efc50>: Failed to establish a new connection: [Errno 111] Connection refused
2017-08-11 23:18:00,150 WARNI [elasticsearch][waitress] POST http://localhost:9200/_bulk [status:N/A request:0.004s]

There is notning on port 9200. But is on 8080 i think. 
I found 9200 port in 3 files:
venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py:    def __init__(self, host='localhost', port=9200, http_auth=None,
venv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:    def __init__(self, host='localhost', port=9200, http_auth=None,
venv/lib/python2.7/site-packages/elasticsearch/connection/base.py:    def __init__(self, host='localhost', port=9200, use_ssl=False, url_prefix='', timeout=10, **kwargs):

It is default 9200. 
I can't find settings for this. 
Maybe you know where it is ?

**Comment by vincentfretin** [comment]
9200 is the default port for elasticsearch. When you have this error, it generally means elasticsearch failed to start, see the logs:
`supervisorctl tail -f elasticsearch` for stdout and
`supervisorctl tail -f elasticsearch stderr` for stderr

Can you verify this?
`lsb_release -i` should give Debian in it and
you should have a file /etc/sysctl.d/vm.max_map_count.conf containing "vm.max_map_count=262144"

`supervisorctl status` and elasticsearch should be in the state STARTED.
Try to do `supervisorctl start elasticsearch` if it's not the case.

**Comment by vincentfretin** [comment]
We didn't change the default port for elasticsearch, so you can't change it currently in the settings.

**Comment by kamiljaszczynski** [comment]
cat  /etc/sysctl.d/vm.max_map_count.conf
vm.max_map_count=262144

We move to Ubuntu. On debian when run command
643  source venv/bin/activate
  644  supervisord
Server stopped - there is no posibility to connect by ssh and console not
reac :>
On ubuntu instlalation Was ok and we don't need change cyrpto and
pyOpenSSL.



supervisorctl status
(venv) assembl@vps272657:~/assembl$ supervisorctl status
celery_imap                      STOPPED   Not started
celery_notification_dispatch     RUNNING   pid 4444, uptime 10:46:25
celery_notify                    STOPPED   Not started
celery_notify_beat               STOPPED   Not started
celery_translate                 STOPPED   Not started
changes_router                   RUNNING   pid 4433, uptime 10:46:30
dev:gulp                         RUNNING   pid 9948, uptime 0:00:28
dev:pserve                       RUNNING   pid 9950, uptime 0:00:28
dev:webpack                      RUNNING   pid 9949, uptime 0:00:28
edgesense                        STOPPED   Not started
elasticsearch                    RUNNING   pid 1658, uptime 10:56:20
maintenance_uwsgi                STOPPED   Not started
metrics                          STOPPED   Not started
metrics_py                       STOPPED   Not started
prod:uwsgi                       RUNNING   pid 9978, uptime 0:00:23
source_reader                    STOPPED   Not started
